Feature/update user
l-dmitry94/aqua-track pull request #9
Opened 2024-08-26 15:11 UTC by l-dmitry94

https://app.clickup.com/t/8695ery0j

2024-08-26 19:20 UTC, liubapohudina commented
Fix the ability to add more than one file in a single request when updating user data.

2024-08-26 20:14 UTC, sivlvy requested changes
Fix the ability to add more than one file in a single request when updating user data.

2024-08-27 08:09 UTC, l-dmitry94 commented
> Fix the ability to add more than one file in a single request when updating user data.

Done

2024-08-27 09:18 UTC, liubapohudina approved these changes

2024-08-27 09:29 UTC, liubapohudina approved these changes

2024-08-27 09:31 UTC, merged